
    const productList=
    
    [
        {
            id:0,
            productfor:"men",
            brand:"Wildstone",
            img:"perfumes/men1.jpg",
            name:"Wildstone Ultra Sensual perfume",
            quantity:"50ml",
            price:219,
            dollaramount:3,
            description:"Wildstone Ultra sensual 5-6 hours lasting perfume for men."
        },
        {
            id:1,
            productfor:"men",
            brand:"Wildstone",
            img:"perfumes/men2.png",
            name:"Wildstone Eau De Parfume",
            quantity:"100ml",
            price:799,
            dollaramount:10.95,
            description:"One of our all time favourite."
        },
        {
            id:2,
            productfor:"men",
            brand:"Fogg",
            img:"perfumes/men3.jpg",
            name:"Impressio Eau De perfume",
            quantity:"100ml",
            price:499,
            dollaramount:6.84,
            description:"Fogg scent beautiful secret,fragrance classification:Eau De perfume,fragrance."
        },
        {
            id:3,
            productfor:"men",
            brand:"Denver",
            img:"perfumes/men4.jpg",
            name:"Hamilton Honour Eau De parfum",
            quantity:"100ml",
            price:410,
            dollaramount:5.62,
            description:"Blue perfume,Skin friendly,Natural fragrance"
        },
        {
            id:4,
            productfor:"men",
            brand:"Park Avenue",
            img:"perfumes/men5.jpg",
            name:"Park Avenue Eau De perfume,Euphoria",
            quantity:"50ml",
            price:380,
            dollaramount:5.21,
            description:"*Rich masculine fragrances. *Ideal for day and evening wear. "
        },
        {
            id:5,
            productfor:"men",
            brand:"Park Avenue",
            img:"perfumes/men6.jpg",
            name:"Park Avenue Eau De perfume,Harmony",
            quantity:"100ml",
            price:679,
            dollaramount:9.31,
            description:"*Rich masculine fragrances. *Ideal for day and evening wear."
        },
        {
            id:6,
            productfor:"men",
            brand:"Villain",
            img:"perfumes/men7.jpg",
            name:"Villain perfume Eau De parfume,woody & spicy",
            quantity:"100ml",
            price:563,
            dollaramount:7.72,
            description:"A strong yet earthy note that lasts longer than all the dark clouds in your head."
        },
        {
            id:7,
            productfor:"men",
            brand:"Villain",
            img:"perfumes/men8.jpg",
            name:"Villain Hydra perfume",
            quantity:"100ml",
            price:569,
            dollaramount:7.80,
            description:"Use this perfume for long lasting freshness & energy to go strong , day & night."
        },
        {
            id:8,
            productfor:"men",
            brand:"Yardley",
            img:"perfumes/men9.jpg",
            name:"Yardley Gentleman Classic Eau De Toilette",
            quantity:"100ml",
            price:1500,
            dollaramount:20.55,
            description:"the gentleman classic EDT from the House of Yardley is a signature."
        },
        {
            id:9,
            productfor:"men",
            brand:"McPherson",
            img:"perfumes/men10.jpg",
            name:"Men black Isle Eau De parfum",
            quantity:"100ml",
            price:799,
            dollaramount:10.95,
            description:"Woody fragrance long lasting."
        },
        {
            id:10,
            productfor:"men",
            brand:"Ustraa",
            img:"perfumes/men11.jpg",
            name:"Ustraa Scuba Cologne",
            quantity:"100ml",
            price:519,
            dollaramount:7.11,
            description:"Long lasting fragrance that contains 3x more perfume than deodorant."
        },
        {
            id:11,
            productfor:"men",
            brand:"Ustraa",
            img:"perfumes/men12.jpg",
            name:"Ustraa Cologne After Dark perfume",
            quantity:"100ml",
            price:559,
            dollaramount:7.66,
            description:"Long lasting fragrance that contains 3x more perfume than deodorant."
        },
        {
            id:12,
            productfor:"men",
            brand:"Rasasi",
            img:"perfumes/men13.jpg",
            name:"Rasasi all Dareej perfume",
            quantity:"100ml",
            price:1550,
            dollaramount:12.24,
            description:"The intoxicating & seductive notes of animatic musk are caressed by plums of dark and smoky exoctic patchouli."
        },
        {
            id:13,
            productfor:"men",
            brand:"Engage",
            img:"perfumes/men14.jpg",
            name:"Yin Eau De parfume",
            quantity:"90ml",
            price:299,
            dollaramount:4.10,
            description:"Give it a good hard shake first to make sure all the ingredients are mixed together before you spray it."
        },
        {
            id:14,
            productfor:"men",
            brand:"Ramsons",
            img:"perfumes/men15.jpg",
            name:"Ramsons extreme fire Eau De perfume",
            quantity:"100ml",
            price:277,
            dollaramount:3.80,
            description:"Long lasting fragrance that captivates your senses.Has aromatic woody notes."
        },
        {
            id:15,
            productfor:"men",
            brand:"Victoria's ",
            img:"perfumes/men16.jpg",
            name:"Victoria's secret Night",
            quantity:"100ml",
            price:900,
            dollaramount:12.33,
            description:"Stand out of the ordinary with this luxury perfume brand which can help you nail your sexiest look in a seamless fashion."
        },
        {
            id:16,
            productfor:"men",
            brand:"B N Perfumes",
            img:"perfumes/men17.jpg",
            name:"Franco",
            quantity:"100ml",
            price:398,
            dollaramount:5.46,
            description:"Perfume for men in cheapest price."
        },
        {
            id:17,
            productfor:"men",
            brand:"Navaratna",
            img:"perfumes/men18.jpg",
            name:"Luxure Man perfume",
            quantity:"100ml",
            price:1450,
            dollaramount:19.87,
            description:"Use this perfume for long lasting freshness & energy to go strong ,day and night."
        },
        {
            id:18,
            productfor:"men",
            brand:"Engage",
            img:"perfumes/men19.jpg",
            name:"Homme Eau De Parfum",
            quantity:"90ml",
            price:299,
            dollaramount:4.10,
            description:"Perfect gift for the intensely charming alpha male with timeless & classic appeal."
        },
        {
            id:19,
            productfor:"men",
            brand:"Villain",
            img:"perfumes/men20.jpg",
            name:"Snake perfume",
            quantity:"100ml",
            price:699,
            dollaramount:9.58,
            description:"Made for the mysterious & masculine villain .For long lasting & unique fragrance."
        },
        {
            id:20,
            productfor:"men",
            brand:"Beardo",
            img:"perfumes/men21.jpg",
            name:"Beardo Dark side perfume",
            quantity:"100ml",
            price:645,
            dollaramount:8.84,
            description:"Premium long lasting and unique fragrance ,fresh & woody."
        },
        {
            id:21,
            productfor:"men",
            brand:"Rasasi",
            img:"perfumes/men22.jpg",
            name:"Royal Blue EDP perfume",
            quantity:"75ml",
            price:1195,
            dollaramount:16.37,
            description:"The intoxicating and seductive notes of animatic musk are caressed by plums of dark and smoky exoctic patchouli."
        },
        {
            id:22,
            productfor:"men",
            brand:"CFS",
            img:"perfumes/men23.jpeg",
            name:"Wild Sandal Perfume",
            quantity:"100ml",
            price:330,
            dollaramount:4.53,
            description:"Premium quality perfume 1 unit of CFS Wild Sandal Perfume, 100ml. Perfume for men Long lasting fragrance Fragrance to keep you fresh all day long."
        },
        {
            id:23,
            productfor:"men",
            brand:"Beardo",
            img:"perfumes/men24.jpg",
            name:"Beardo Godfather Perfume",
            quantity:"100ml",
            price:645,
            dollaramount:8.84,
            description:"A premium perfume that has a strong and masculine fragrance that lasts longer than other perfumes."
        },
        {
            id:24,
            productfor:"men",
            brand:"Beardo",
            img:"perfumes/men25.jpg",
            name:"Beardo Origin Perfume",
            quantity:"100ml",
            price:630,
            dollaramount:8.64,
            description:"Refreshing and manly fragrance,Long lasting,Strong Aqua and Musky Tones."
        },
        {
            id:25,
            productfor:"men",
            brand:"Burberry",
            img:"perfumes/men26.jpg",
            name:"Mr. Burberry Indigo EDT",
            quantity:"100ml",
            price:2313,
            dollaramount:31.68,
            description:"Burberry is a world-famous British fashion house creating luxury products for the fashion, cosmetics, and perfume industries."
        },
        {
            id:26,
            productfor:"men",
            brand:"Naytica",
            img:"perfumes/men27.jpg",
            name:"Nautica Blue EDT Spray",
            quantity:"100ml",
            price:1510,
            dollaramount:20.69,
            description:"The nose behind this fragrance is Maurice Roucel. Top notes are pineapple, peach and bergamot; middle notes are jasmine and water lily; base notes are sandalwood, musk and cedar."
        },
        {
            id:27,
            productfor:"men",
            brand:"EvaflorParis",
            img:"perfumes/men28.jpg",
            name:"Evaflor Whisky EDT",
            quantity:"100ml",
            price:620,
            dollaramount:8.50,
            description:"This man is handsome and fashionable with an authentic style that makes him irresistible. WHISKY VINTAGE is the signature of his originality."
        },
        {
            id:28,
            productfor:"men",
            brand:"La French",
            img:"perfumes/men29.jpg",
            name:"La French Luxure Oud",
            quantity:"100ml",
            price:490,
            dollaramount:6.72,
            description:"It is very popular among younger hearts for the classic, elegant and timeless appeal of these exquisite fragrances. A Non- allergenic Fragrance that doesn’t affects your skin."
        },
        {
            id:29,
            productfor:"men",
            brand:"Fogg",
            img:"perfumes/men30.jpg",
            name:"Xtremo Scent",
            quantity:"100ml",
            price:299,
            dollaramount:4.10,
            description:"Long lasting fragrance. Fragrance stays for almost 4-5 hours of application."
        },
        {
            id:30,
            productfor:"men",
            brand:"Fogg",
            img:"perfumes/men31.jpg",
            name:"Intensio",
            quantity:"100ml",
            price:499,
            dollaramount:6.84,
            description:"Long lasting fragrance."
        },
        
        {
            id:31,
            productfor:"women",
            brand:"Fogg",
            img:"perfumes/women1.jpg",
            name:"I am queen ",
            quantity:"100ml",
            price:305,
            dollaramount:4.18,
            description:"Long lasting fragrance .Give it good hard shake.You should hold the can approximately 15cm from your body as you spray it."
        },
        {
            id:32,
            productfor:"women",
            brand:"Engage",
            img:"perfumes/women2.jpg",
            name:"Femme Eau De parfum",
            quantity:"90ml",
            price:499,
            dollaramount:6.84,
            description:"Fragrance concentration 10%.Apply on pulse points for an intense long lasting trail."
        },
        {
            id:33,
            productfor:"women",
            brand:"Senorita",
            img:"perfumes/women3.jpg",
            name:"Bella vita organic senorita perfume",
            quantity:"100ml",
            price:499,
            dollaramount:6.84,
            description:"Long lasting fruity fragrance for daywear at work and also for quiet romantic evening."
        },
        {
            id:34,
            productfor:"women",
            brand:"Secret Love",
            img:"perfumes/women4.jpg",
            name:"Body Cupid secret love perfume",
            quantity:"100ml",
            price:540,
            dollaramount:7.40,
            description:"Premium fragrance for women who like smell good .Long lasting fragrance for day and evening wear."
        },
        {
            id:35,
            productfor:"women",
            brand:"Ajmal",
            img:"perfumes/women5.jpg",
            name:"Senora EDP floral perfume",
            quantity:"75ml",
            price:1200,
            dollaramount:16.44,
            description:"Long lasting fruity fragrance for daywear at work and also for quiet romantic evening."
        },
        {
            id:36,
            productfor:"women",
            brand:"SKINN",
            img:"perfumes/women6.jpg",
            name:"Skinn Nude perfume",
            quantity:"50ml",
            price:1429,
            dollaramount:19.58,
            description:"100% original product by Skinn,Titan."
        },
        {
            id:37,
            productfor:"women",
            brand:"Engage",
            img:"perfumes/women7.jpg",
            name:"Yang Eau De parfum",
            quantity:"90ml",
            price:389,
            dollaramount:5.33,
            description:"Perfect gift for the women of today who makes a statement wherever she goes."
        },
        {
            id:38,
            productfor:"women",
            brand:"CFS",
            img:"perfumes/women8.jpg",
            name:"Cfs Floral Rose Lady Perfume",
            quantity:"100ml",
            price:299,
            dollaramount:4.10,
            description:"100% Quality Guarantee Perfumes, Indian Perfumes, Branded Perfumes, Best Perfume, Long Lasting Perfume."
        },
        {
            id:39,
            productfor:"women",
            brand:"Ajmal",
            img:"perfumes/women9.jpg",
            name:"Ajmal Regina EDP",
            quantity:"100ml",
            price:1316,
            dollaramount:18.03,
            description:"Regina is a creation for the girl of the millennial. It is formulated for the fashion conscious women who is playful, outgoing and has a refreshing approach towards all things that life has to offer."
        },
        {
            id:40,
            productfor:"women",
            brand:"SKINN",
            img:"perfumes/women10.jpg",
            name:" Titan Sheer Perfume",
            quantity:"50ml",
            price:1499,
            dollaramount:20.55,
            description:"100% original product by Skinn,Titan."
        },
        {
            id:41,
            productfor:"women",
            brand:"Rasasi",
            img:"perfumes/women11.jpeg",
            name:"Blue Lady Perfume EDP Eau de Parfum",
            quantity:"40ml",
            price:595,
            dollaramount:8.16,
            description:"A Very Fresh Floral Bouquet With Citrus Notes And Fruity Touches. The Green Note Gives More Freshness And More Diffusion. The Accord Finishes With A Soft Musky Powdery Effect And A Lasting Woody Note."
        },
        {
            id:42,
            productfor:"women",
            brand:"Rasasi",
            img:"perfumes/women12.jpeg",
            name:" Blue Lady2 Eau de Parfum",
            quantity:"30ml",
            price:705,
            dollaramount:9.66,
            description:"Featuring a stunning packaging, the scent will last long even after hours of applying and keep you smelling fresh all day long. It has a fresh fragrance that will leave you smelling good by raising your confidence."
        },
        {
            id:43,
            productfor:"women",
            brand:"BN Parfums",
            img:"perfumes/women13.jpeg",
            name:"Magic Couture Eau de Toilette",
            quantity:"100ml",
            price:320,
            dollaramount:4.39,
            description:"Perfume for women in cheapest price."
        },
        {
            id:44,
            productfor:"women",
            brand:"Yardley London",
            img:"perfumes/women14.jpeg",
            name:" Morning Dew (Daily Wear Perfume) Eau de Toilette",
            quantity:"100ml",
            price:510,
            dollaramount:6.99,
            description:"Waking up to a picture perfect Dewy Morning in London, overlooking the Thames, as the sun caresses the smile on your face and sets you in playful cheery start. "
        },
        {
            id:45,
            productfor:"women",
            brand:"Yardley London",
            img:"perfumes/women15.jpeg",
            name:"Country Breeze (Daily Wear Perfume) Eau de Toilette ",
            quantity:"100ml",
            price:510,
            dollaramount:6.99,
            description:" This fragrance takes you on a mesmerizing journey through the fresh fragrances of English meadows. "
        },
        {
            id:46,
            productfor:"women",
            brand:"Yardley London",
            img:"perfumes/women16.jpeg",
            name:"Autumn Bloom (Daily Wear Perfume) Eau de Toilette",
            quantity:"100ml",
            price:510,
            dollaramount:6.99,
            description:"This fragrance combines the richness of oriental scent with the vibrancy of fresh flowers."
        },
        {
            id:47,
            productfor:"women",
            brand:"Yardley ",
            img:"perfumes/women17.jpeg",
            name:"English Lavender Perfume",
            quantity:"125ml",
            price:1039,
            dollaramount:14.24,
            description:" English Lavender Eau De Toilette combines floral freshness of lavender with caring accords of musk to create a delicate and sophisticated fragrance that is a pleasure to wear."
        },
        {
            id:48,
            productfor:"women",
            brand:"CFS",
            img:"perfumes/women18.jpg",
            name:"Aqua Blue Eau de parfum",
            quantity:"100ml",
            price:399,
            dollaramount:5.47,
            description:"It is very popular among younger hearts for the classic, elegant and timeless appeal of these exquisite fragrances."
        },
        {
            id:49,
            productfor:"women",
            brand:"Antonio Banderas",
            img:"perfumes/women19.jpg",
            name:"Her Secret Temptation Eau de Toilette",
            quantity:"50ml",
            price:2555,
            dollaramount:34.99,
            description:"Her Secret Temptation is a wonderful oriental-floral fragrance for women"
        },
        {
            id:50,
            productfor:"women",
            brand:"Secret",
            img:"perfumes/women20.jpg",
            name:"Secret Temptation Romance Perfume ",
            quantity:"50ml",
            price:300,
            dollaramount:4.11,
            description:"Secret Temptation Romance Eau de Parfum for women is a mix of hyacinth, jasmine, neroli and orange blossom. As you set out to write a love story, this fragrance will be an epic romance between you and your dreams."
        },
        {
            id:51,
            productfor:"women",
            brand:"Layer'r Wottagirl",
            img:"perfumes/women21.jpg",
            name:" Adore Perfume Spray",
            quantity:"100ml",
            price:450,
            dollaramount:6.17,
            description:"LAYER’R Wottagirl Adore Perfume Spray is an intimate mix of fresh apple, lavender and cedarwood. A fragrance you will just adore!"
        },
        {
            id:52,
            productfor:"women",
            brand:"Engage",
            img:"perfumes/women22.jpg",
            name:"W1 Perfume Spray",
            quantity:"120ml",
            price:160,
            dollaramount:2.20,
            description:"Give it a good hard shake first to make sure all the ingredients are mixed together before you spray it. You should hold the can approximately 15cm from your body or clothes as you spray it."
        },
        {
            id:53,
            productfor:"women",
            brand:"Engage",
            img:"perfumes/women23.jpg",
            name:"W2 Perfume Spray",
            quantity:"120ml",
            price:160,
            dollaramount:2.20,
            description:"Give it a good hard shake first to make sure all the ingredients are mixed together before you spray it. You should hold the can approximately 15cm from your body or clothes as you spray it."
        },
        {
            id:54,
            productfor:"women",
            brand:"Fogg",
            img:"perfumes/women24.jpg",
            name:"Make My Day Scent ",
            quantity:"100ml",
            price:499,
            dollaramount:6.84,
            description:"Soothing experience throughout the day,Ensures you 800 sprays,Consists of refreshing,Long lasting fragrance."
        },
        {
            id:55,
            productfor:"women",
            brand:"Hugo Boss",
            img:"perfumes/women25.jpg",
            name:"Hugo Boss Femme",
            quantity:"75ml",
            price:2190,
            dollaramount:29.99,
            description:"It is very popular among younger hearts for the classic, elegant and timeless appeal of these exquisite fragrances."
        },
        {
            id:56,
            productfor:"women",
            brand:"Ali",
            img:"perfumes/women26.jpg",
            name:"OEM ODM Uever",
            quantity:"100ml",
            price:250,
            dollaramount:3.40,
            description:"Fruity Fragrance,Classic Woods, Fresh Florals, Fruity Florals, Warm Woods,Natural Ingredients."
        },
        {
            id:57,
            productfor:"women",
            brand:"ZARA",
            img:"perfumes/women27.jpg",
            name:"ZARA RED VANILLA",
            quantity:"100ml",
            price:780,
            dollaramount:10.69,
            description:"Long lasting fragrance-Effectively stays longer than 24 hours. Doesn't mark or stain clothing Fragrance"
        },
        {
            id:58,
            productfor:"women",
            brand:"Ajaml",
            img:"perfumes/women28.jpg",
            name:"Ajmal Diza EDP Fresh Perfume ",
            quantity:"100ml",
            price:880,
            dollaramount:12.06,
            description:"The fragrance further cosies up with an opulent heart filled up with Fresh Luxurious Exotic Florals. This masterpiece is further locked up with warm woods in combination with ever lingering musks."
        },
        {
            id:59,
            productfor:"women",
            brand:"Kim Kardashian",
            img:"perfumes/women29.jpg",
            name:"Kim Kardashian Glam Eau De Parfum Spray",
            quantity:"100ml",
            price:1640,
            dollaramount:22.45,
            description:"This women's fragrance possesses a blend of Pink Watermelon, Sparkling Citrus, Juicy Berries, Star Jasmine, Rose Absolute ORPUR, Egyptian Tuberose, Orris Butter, Creamy Sandalwood and Sensual Musk."
        },
        {
            id:60,
            productfor:"women",
            brand:"Lomani",
            img:"perfumes/women30.jpg",
            name:"Lomani Sensual Paris perfume",
            quantity:"100ml",
            price:890,
            dollaramount:12.20,
            description:"Sensual Paris Eau de perfume,vaporisateur Natural Spray"
        },
        {
            id:61,
            productfor:"women",
            brand:"TFF",
            img:"perfumes/women31.jpg",
            name:"The French Factor Lady Noir Perfume",
            quantity:"100ml",
            price:730,
            dollaramount:10,
            description:"Lady Noir has a unique international fragrance which gives you a luxury French scent.Perfect perfume for special occasions like social or formal events, date, wedding, party and meetings"
        }
       
    ];
    
        
        module.exports.productList=productList; 